version: '3.8'

services:
  discord-tts-bot:
    build:
      context: .
      dockerfile: docker/tts/Dockerfile
    container_name: discord_tts_bot
    # .envファイルから環境変数を読み込む
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
    # コンテナがクラッシュした場合に自動的に再起動する
    restart: unless-stopped
    depends_on:
      - voicevox-engine

  discord-music-bot:
    build:
      context: .
      dockerfile: docker/music/Dockerfile
    container_name: discord_music_bot
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped

  voicevox-engine:
    image: voicevox/voicevox_engine:cpu-latest
    container_name: voicevox_engine
    ports:
      - "127.0.0.1:50021:50021"
    restart: unless-stopped
